development:
  adapter: postgresql
  encoding: unicode
  database: vanilla_development
  pool: 5
  username: admin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: vanilla_test
  pool: 5
  username: admin
  password: